#!/bin/bash
python DataProcessing/AngloSaxonChronicle/1_transform_Anglo_Saxon_Chronicle_to_document_collection.py
python DataProcessing/AngloSaxonChronicle/2_linguisitc_preprocess_anglo_saxon_chronicle.py

python DataProcessing/AngloSaxonChronicle/3_feature_selection_content_words.py
python DataProcessing/AngloSaxonChronicle/4_recognize_multi_word_expressions.py

python DataProcessing/AngloSaxonChronicle/5_feature_selection_unsupervised.py
python DataProcessing/AngloSaxonChronicle/6_create_tf_idf_document_term_matrix.py
python DataProcessing/AngloSaxonChronicle/7_post_process_document_collection_for_visualization.py
python Experiments/DetectSimilarEntriesAngloSaxonChronicles/1_cluster_document_term_matrix_with_ap.py
python Experiments/DetectSimilarEntriesAngloSaxonChronicles/2_plot_document_term_matrix.py report
python Experiments/DetectSimilarEntriesAngloSaxonChronicles/3_create_heat_map_of_cluster.py
python Experiments/DetectSimilarEntriesAngloSaxonChronicles/4_topic_model.py